server:
  port: 8085

spring:
  application:
    name: usedcar-recommend
  redis:
    host: localhost
    port: 6379

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
